packageExtensions:
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"
  jss-plugin-rule-value-function@*:
    dependencies:
      tiny-warning: "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .\.yarn\releases\yarn-berry.js
